-- MySQL Script generated by MySQL Workbench
-- Mon Sep 25 17:24:32 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema chatnet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema chatnet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chatnet` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `chatnet` ;

-- -----------------------------------------------------
-- Table `chatnet`.`servidores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chatnet`.`servidores` (
  `id_servidor` INT NOT NULL AUTO_INCREMENT,
  `nombre_servidor` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_servidor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chatnet`.`canales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chatnet`.`canales` (
  `id_canal` INT NOT NULL AUTO_INCREMENT,
  `nombre_canal` VARCHAR(100) NOT NULL,
  `id_servidor` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_canal`),
  INDEX `id_servidor` (`id_servidor` ASC) VISIBLE,
  CONSTRAINT `canales_ibfk_1`
    FOREIGN KEY (`id_servidor`)
    REFERENCES `chatnet`.`servidores` (`id_servidor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chatnet`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chatnet`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(50) NOT NULL,
  `contraseña` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `imagen_perfil` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chatnet`.`mensajes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chatnet`.`mensajes` (
  `id_mensaje` INT NOT NULL AUTO_INCREMENT,
  `contenido` TEXT NOT NULL,
  `fecha` DATETIME NULL DEFAULT NULL,
  `id_usuario_emisor` INT NULL DEFAULT NULL,
  `id_canal` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_mensaje`),
  INDEX `id_usuario_emisor` (`id_usuario_emisor` ASC) VISIBLE,
  INDEX `id_canal` (`id_canal` ASC) VISIBLE,
  CONSTRAINT `mensajes_ibfk_1`
    FOREIGN KEY (`id_usuario_emisor`)
    REFERENCES `chatnet`.`usuarios` (`id_usuario`),
  CONSTRAINT `mensajes_ibfk_2`
    FOREIGN KEY (`id_canal`)
    REFERENCES `chatnet`.`canales` (`id_canal`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chatnet`.`user_server`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chatnet`.`user_server` (
  `id` INT NOT NULL,
  `usuarios_id_usuario` INT NOT NULL,
  `servidores_id_servidor` INT NOT NULL,
  PRIMARY KEY (`usuarios_id_usuario`, `servidores_id_servidor`),
  INDEX `fk_user_server_usuarios1_idx` (`usuarios_id_usuario` ASC) VISIBLE,
  INDEX `fk_user_server_servidores1_idx` (`servidores_id_servidor` ASC) VISIBLE,
  CONSTRAINT `fk_user_server_servidores1`
    FOREIGN KEY (`servidores_id_servidor`)
    REFERENCES `chatnet`.`servidores` (`id_servidor`),
  CONSTRAINT `fk_user_server_usuarios1`
    FOREIGN KEY (`usuarios_id_usuario`)
    REFERENCES `chatnet`.`usuarios` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
